---
driver:
  name: docker

provisioner:
  name: ansible_playbook
  roles_path: roles
  require_ruby_for_busser: true
  require_ansible_source: false
  require_ansible_repo: false
  require_ansible_omnibus: false
  hosts: test

platforms:
  - name: ubuntu-14.04
    driver_config:
      require_chef_omnibus: false
      dockerfile: /home/vagrant/Dockerfile

busser:
  ruby_bindir: /usr/bin

suites:
  - name: default
