forge "http://forge.puppetlabs.com"

mod "zack/r10k"
mod "puppetlabs/stdlib"
mod "puppetlabs/ruby"
mod "puppetlabs/firewall"
mod "puppetlabs/gcc"
mod "puppetlabs/pe_gem"
mod "croddy/make"
mod "puppetlabs/inifile"
mod "puppetlabs/vcsrepo"
mod "puppetlabs/git"
mod "gentoo/portage"

